No "dev" should appear in package.json version number
python-restx/flask-restx pull request #317
Opened 2021-05-18 23:18 UTC by xuhdev

This is the error message I got when I ran `inv assets`:

    npm WARN Invalid version: "0.4.1.dev"
    npm WARN flask-restx No description
    npm WARN flask-restx No repository field.
    npm WARN flask-restx No README data
    npm WARN flask-restx No license field.

2021-05-18 23:20 UTC, xuhdev commented
The ill-formed version number makes development annoying (always have to manually remove `.dev` if `inv assets` is to be invoked).
`package.json` doesn't allow an easy way to add comment. I'm happy to add a test for `inv assets` if you prefer this.

2021-05-19 19:14 UTC, j5awry commented
Thank you for the PR. However, this doesn't fix the issue, it only fixes immediate installs. Furthermore, it will incorrectly set this to be version 0.4.1, when it needs to be a pre-release version. we use `bumpr` (https://github.com/noirbizarre/bumpr) for our automation right now. The file that will need to be updated to correct things is: https://github.com/python-restx/flask-restx/blob/master/bumpr.rc

any change proposal here will need to work in our release workflow: https://github.com/python-restx/flask-restx/blob/master/CONTRIBUTING.rst#release-process

2021-05-19 19:15 UTC, j5awry requested changes

2021-05-19 19:15 UTC, j5awry commented on package.json
> +  "version": "0.4.1",
this needs to stay a pre-release version. according to the docs, it needs to begin with a hyphen, then have dots: [0-9A-Za-z-]

https://semver.org/#spec-item-9

2021-05-19 21:41 UTC, xuhdev commented
Thanks for the explanation. I checked out bumpr's documentation, it doesn't seem like it can use `-` to connect the suffix. I also tried to manually add the dash, but seems like bumpr would mess it up. Its [regex option](https://bumpr.readthedocs.io/en/latest/rcfile.html#bumpr) also doesn't seem to support 2 different format.

The easiest solution seems to put a warning message or a hack in the version string in the `assets` task. How does it sound for you?

2021-05-20 13:01 UTC, j5awry commented
There's also an open bug against `bumpr` : https://github.com/noirbizarre/bumpr/issues/39

I'm assuming that noirbizarre isn't making updates. I've suggested moving off `bumpr` in the past, and I think this may be the breaking point. Do you have suggestions of other similar projects? I've used [`versoineer`](https://pypi.org/project/versioneer/) in the past with success. or we could fork `bumpr` and bring in the fixes (or offer to take over some contribution there as well, as we originally did with flask-restplus)

2021-05-20 18:54 UTC, xuhdev commented
I'm using [setuptools_scm](https://pypi.org/project/setuptools-scm/). It generates versions automatically based on the current git tag (for release versions) or how far it is from the last git tag (for dev versions). So, there shouldn't be any need to run any specific command to bump version number, just do git tag. It is maintained by PYPA so the probability of getting abandoned without transition guide is low. But I don't know whether it is possible to get it to work with npm's version string format.

2021-05-24 12:51 UTC, j5awry requested changes

2021-05-24 12:51 UTC, j5awry commented on package.json
> +  "version": "0.4.1",
Good discussion on path forward. But let's get unblocked now while we figure out what to do. Could you set this to "0.4.1-dev" for now. that should conform to the semver requirements for `npm`. 

Next step will be to deal with  either switching tools, getting a PR merged into `bumpr` to follow semver rules rather than custom regex, or making a fork of `bumpr.` But that can be done separately.

2021-05-26 20:06 UTC, j5awry approved these changes

2021-05-27 12:25 UTC, merged