Use the referencing package for resolving schema references
python-restx/flask-restx pull request #560
Opened 2023-09-18 11:42 UTC by foarsitter

For what I found is that the `jsonschema` validators are compatible with the `referencing` package resolvers. 

This change is at least covered by `test_api_payload_strict_verification`. 

Fixes #553

2023-09-19 13:36 UTC, hbusul reviewed
Idk if reviews from a third party gets a pass but anyway changes looks good to me,
I've run our tests using this branch and nothing failed. But this has no changelog, the contributing guideline states that it should contain one

2023-09-19 14:05 UTC, peter-doggart commented
Sure thing. Will have a review of this later this evening. :)

2023-09-19 15:24 UTC, foarsitter commented
Yesterday everything seemed fine: https://github.com/foarsitter/flask-restx/actions/runs/6237094186/job/16929870907 

Today I messed up the branch while on the phone. @hbusul can you see what's the difference?

2023-09-19 15:26 UTC, peter-doggart commented
I think we might run into problems because currently `flask-restx` supports python 3.7 but the new referencing package does not, just looking at the pipelines that ran previously. Can't check right now, but if python 3.7 is end of life we might need to drop support to make this change.

2023-09-19 15:35 UTC, foarsitter commented
Python 3.7 is indeed EOL since 2023-06-27.

2023-09-19 15:40 UTC, hbusul commented
It is not only referencing but also jsonschema that does not support python 3.7 . With 3.7 it does not even import referencing due to a syntax error.  I have nothing against for dropping python 3.7 but I do not know if it should be done with this ticket or it should be announced. What do you think about moving to import statement in try-except and fallback to not supported way but that also gives you time until jsonschema really drops it, maybe to counter that we can fix the version and when we get rid of 3.7 we can unfix the version.

2023-09-24 15:29 UTC, peter-doggart requested changes
I think this is all fine, since I've merged the drop 3.7 PR. However, can you have a look and resolve the remaining conflict (it's on the changelog) I can't fix it because this PR is to merge foarsitter:master.

2023-09-24 19:30 UTC, foarsitter commented
Some tests are failing and I'm unable to find a solution. 

FAILED tests/test_payload.py::PayloadTest::test_validation_with_inheritance
FAILED tests/test_payload.py::PayloadTest::test_validation_on_list

2023-09-25 12:41 UTC, hbusul commented
I'm a bit busy but I will try to look at why those are failing ASAP within this week

2023-10-08 13:13 UTC, foarsitter commented
Did some investigation on the issue today. Seems that we do not need `referencing` after all. `#definitions/Person` is a local pointer to within the document. Adding `resources` to the references `registry` will not help since that adds global reference (i.e. https://yourapi.com/Person). 

Instead of keeping a global registry, I added the `definitions` to the schema that is going to be validated on the fly. In this way the `$ref`'s can be resolved and we do not need an external resolver. 

Note: In order to make the tests succeed I needed to pin flask < 3.0.0. If we will accept this solution that commit has to be removed.

2024-01-15 07:23 UTC, closed without merging

2024-02-01 13:25 UTC, dsrink commented
The last few messages on this PR look strange to me. It seems that this PR was not merged. Could somebody handle this? This issue is bugging me in some of my installations.

2024-02-01 14:54 UTC, foarsitter commented
@dsrink sorry, I deleted the fork. Opened #592 to fix this.